#!/bin/bash
set -e

NETWORK=${TINC_NETWORK:-testvpn}
NODE=${NODE_NAME:-node1}
QUIC_ENABLED=${QUIC_ENABLED:-yes}

echo "================================================"
echo "Starting Tinc Node: $NODE"
echo "Network: $NETWORK"
echo "QUIC Support: $QUIC_ENABLED"
echo "================================================"

# Check if tinc configuration exists, auto-generate if missing
if [ ! -f "/etc/tinc/$NETWORK/tinc.conf" ]; then
    echo "Configuration not found at /etc/tinc/$NETWORK/tinc.conf"
    echo "Auto-generating configuration for node: $NODE"
    echo ""

    # Run tinc init to generate config with all options documented
    tinc -n "$NETWORK" init "$NODE"

    if [ ! -f "/etc/tinc/$NETWORK/tinc.conf" ]; then
        echo "ERROR: Failed to generate configuration"
        exit 1
    fi

    echo ""
    echo "Configuration generated successfully!"
    echo "================================================"
fi

# Show configuration
echo ""
echo "=== Tinc Configuration ==="
cat "/etc/tinc/$NETWORK/tinc.conf"
echo "=========================="
echo ""

# Check if host files exist
if [ -d "/etc/tinc/$NETWORK/hosts" ]; then
    echo "=== Available Host Files ==="
    ls -la "/etc/tinc/$NETWORK/hosts/"
    echo "============================"
    echo ""
fi

# Create TUN device if not exists
if [ ! -e /dev/net/tun ]; then
    echo "Creating /dev/net/tun"
    mkdir -p /dev/net
    mknod /dev/net/tun c 10 200
    chmod 600 /dev/net/tun
fi

# QUIC certificates are now auto-generated by tinc itself
# See cert_autogen.c for implementation
if [ "$QUIC_ENABLED" = "yes" ]; then
    echo "QUIC mode enabled - certificates will be auto-generated by tinc if missing"
fi

# Display MsQuic library information
echo "=== MsQuic Library Info ==="
if ldconfig -p | grep -q libmsquic; then
    ldconfig -p | grep libmsquic
    echo "MsQuic library loaded successfully"
else
    echo "WARNING: MsQuic library not found in ldconfig cache"
    echo "Attempting to locate manually..."
    find /usr -name "libmsquic.so*" 2>/dev/null || echo "Not found"
fi
echo "============================"
echo ""

# Execute tincd with all arguments and network name
echo "Starting tincd with network: $NETWORK"
echo "Debug level: ${TINC_DEBUG_LEVEL:-3} (default: 3, connection logging only)"
echo ""
exec tincd -n "$NETWORK" -D -d${TINC_DEBUG_LEVEL:-3}
