Name = testnode4
Port = 443
DeviceType = tun
Interface = tinc0
Mode = router
TransportMode = quic
QUICJitterMaxUs = 0
QUICStreamCount = 6
QUICKeepaliveMin = 5
QUICKeepaliveMax = 15
QUICKeepaliveSize = 64
QUICHTTP3Masquerading = yes
QUICPaddingMode = off
QUICDebugLevel = 0
QUICTrustPublicCerts = yes
PingInterval = 10
PingTimeout = 5
MTU = 1400
AutoConnect = yes

# VPN Address assigned during join
VPNAddress = 10.0.0.4/24

# Connect to inviter node
ConnectTo = node1
